import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React from "react";
import {
  Box,
  Flex,
  Text,
  VStack,
  FormControl,
  FormLabel,
  InputGroup,
  InputLeftAddon,
  Input,
  Button,
  useToast,
} from "@chakra-ui/react";
import { ChakraProvider } from "@chakra-ui/react";
// import { TwitterLogo } from "./TwitterLogo";

export default function Home() {
  // TODO: Implement the API call and autocomplete logic here
  const toast = useToast();

  const handleSubmit = (e) => {
    e.preventDefault();
    // TODO: Check if the Twitter handle is valid and make the API call
    // If not found, show an error toast
    toast({
      title: "Error",
      description: "Twitter handle not found.",
      status: "error",
      duration: 5000,
      isClosable: true,
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack
        minH="100vh"
        justifyContent="space-between"
        bgGradient="linear(to-r, teal.500, green.500)"
        color="white"
      >
        <Box as="header" py={4}>
          {/* TODO: Add your header content here */}
        </Box>

        <VStack as="main" spacing={4}>
          <Text fontSize="4xl">Title</Text>
          <Text fontSize="2xl">Subtitle</Text>
          <Text>Some text goes here</Text>

          <FormControl onSubmit={handleSubmit}>
            <FormLabel htmlFor="twitterHandle">Twitter handle</FormLabel>
            <InputGroup>
              <InputLeftAddon>{/* <TwitterLogo /> */}</InputLeftAddon>
              <Input
                id="twitterHandle"
                type="text"
                // TODO: Add autocomplete logic here
              />
            </InputGroup>
            <Button type="submit" mt={4} colorScheme="blue">
              Get instructions
            </Button>
          </FormControl>
        </VStack>

        <Box as="footer" py={4}>
          {/* TODO: Add your footer content here */}
        </Box>
      </VStack>
    </>
  );
}
